spring.application.name=lv2-final-mission
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:database
jwt.secretKey=Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
jwt.expiration=3600000
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never
spring.jpa.ddl-auto=create-drop
external.name.secretKey=test
external.name.baseUrl=test
external.name.connect-timeout=1
external.name.read-timeout=1