spring.application.name=lv2-final-mission

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:database

security.jwt.token.secret-key=wn7OCzJrGc+Ze3wFRCwLV0Nn0hm7sr+Oo/ooLDREz6ZtkgLgQLguluevBe08qsiavRTc6GJ+mccLHeL6xMFzaw
security.jwt.token.expire-length=3600000

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true

api.holiday.base-url=http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService
api.holiday.service-key=GsCSc1zx%2F2S9NbG7pehp32d4ftyFpX4mMd%2FjFSFZYx6ujG0ruVNWFBuHUwLB7NH1izSsUG%2FG7LQHpmJMDvxaYQ%3D%3D
