spring.application.name=lv2-final-mission
security.holiday.api.service-key=GbJmfStUjTMn4fHb4w7jqlBGGIk9MnVLW7W22Ig1D6h3A7YaxvfDrAHjHhVGk1a%2BGhIcYysrZ%2BUovxZExR%2BmkA%3D%3D
security.jwt.token.secret-key=Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
security.jwt.token.expire-length=3600000
