spring.application.name=lv2-final-mission
spring.config.import=optional:file:.env[.properties]
spring.sql.init.mode=always
spring.jpa.properties.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:final
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
data-secret-key=${DATA_SECRET_KEY}
