drop table if exists member cascade;
drop table if exists nickname_reservation cascade;

create table member
(
    id       bigint generated by default as identity,
    email    varchar(255),
    password varchar(255),
    primary key (id)
);

create table nickname_reservation
(
    id        bigint generated by default as identity,
    member_id bigint,
    name      varchar(255),
    status    enum ('CONFIRM','RESERVE'),
    primary key (id)
);

alter table if exists nickname_reservation add constraint FKi2p3udii3y47t7bqd03dgu56n foreign key (member_id) references member;
